version: "3"
services:
  reverseproxy:
      image: dockerkomarina/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-feed
        - backend-user
  backend-user:
    image: dockerkomarina/udacity-restapi-user
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8100"
  backend-feed:
    image: dockerkomarina/udacity-restapi-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_BUCKET
      JWT_TOKEN: $JWT_TOKEN
      URL: "http://localhost:8100"
  frontend:
    image: dockerkomarina/udacity-frontend:local
    ports:
      - "8100:80"